-- ADR-0022: cost of the audit retention purge and of keeping 90 days of audit rows (#114).
-- Builds a copy of app.audit (same columns, PK and IX_audit_at) in a throwaway database, fills it with synthetic
-- rows, then times the purge statement the API runs (EF ExecuteDelete: DELETE ... WHERE at < @cutoff).
-- Local throwaway Postgres only (trust auth, nothing persisted); never Neon or production. See the ADR for the command.
--
-- Volume: :rows_per_day rows a day for 120 days. 10,000/day is a busy demo (about 7 rows a minute around the clock;
-- the per-user limit is 60/min, so a handful of active users all day).
\set ON_ERROR_STOP on
\if :{?rows_per_day}
\else
  \set rows_per_day 10000
\endif

DROP TABLE IF EXISTS audit;
CREATE TABLE audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_audit" PRIMARY KEY,
    at timestamp with time zone NOT NULL,
    kind character varying(16) NOT NULL,
    user_name character varying(256),
    endpoint character varying(256) NOT NULL,
    status integer NOT NULL,
    rows integer,
    ms integer NOT NULL,
    cache character varying(8)
);
CREATE INDEX "IX_audit_at" ON audit (at);

-- 120 days ending at a fixed "now"; synthetic users and endpoints like the real ones.
INSERT INTO audit (at, kind, user_name, endpoint, status, rows, ms, cache)
SELECT timestamptz '2026-10-08 12:00+00' - (g * (interval '120 days' / (:rows_per_day * 120))),
       'request',
       'viewer-' || (g % 7) || '@example.com',
       (ARRAY['GET /api/positions/rows', 'GET /api/positions/summary', 'GET /api/meta', 'GET /api/presets/{page}'])[1 + g % 4],
       200, 500, 12 + g % 90, (ARRAY['HIT', 'MISS'])[1 + g % 2]
FROM generate_series(1, :rows_per_day * 120) AS g;
VACUUM ANALYZE audit;

\echo '--- size with 120 days'
SELECT count(*) AS rows, pg_size_pretty(pg_total_relation_size('audit')) AS total,
       round(pg_total_relation_size('audit')::numeric / count(*), 1) AS bytes_per_row
FROM audit;

\echo '--- steady state: one daily purge (deletes the oldest day: 119 -> 120 days ago)'
BEGIN;
EXPLAIN (ANALYZE, BUFFERS, COSTS OFF, SUMMARY ON)
DELETE FROM audit WHERE at < timestamptz '2026-10-08 12:00+00' - interval '119 days';
ROLLBACK;

\echo '--- backlog: first purge with a 90-day window (deletes 30 days)'
EXPLAIN (ANALYZE, BUFFERS, COSTS OFF, SUMMARY ON)
DELETE FROM audit WHERE at < timestamptz '2026-10-08 12:00+00' - interval '90 days';

\echo '--- nothing to delete (the purge right after a purge)'
EXPLAIN (ANALYZE, BUFFERS, COSTS OFF, SUMMARY ON)
DELETE FROM audit WHERE at < timestamptz '2026-10-08 12:00+00' - interval '90 days';

VACUUM ANALYZE audit;
\echo '--- size with 90 days (after the purge and a vacuum; space is reused, not returned to the OS)'
SELECT count(*) AS rows, pg_size_pretty(pg_total_relation_size('audit')) AS total FROM audit;
