-- ADR-0022: cost of the audit retention purge and of keeping 90 days of audit rows (#114).
-- Builds a copy of app.audit (same columns, PK and IX_audit_at) in a throwaway database, fills it with synthetic
-- rows, then times the statements the API runs (AuditRetention.PurgeIfDueAsync).
-- Local throwaway Postgres only (trust auth, nothing persisted); never Neon or production. See the ADR for the commands.
--
-- Volume: :rows_per_day rows a day for 120 days. 10,000/day is a busy demo (about 7 rows a minute around the clock;
-- the per-user limit is 60/min, so a handful of active users all day).
--
-- Steps (-v step=…; default "all", one warm run): fill | daily | backlog | batch | batchin | empty | all.
-- A cold run does "fill", then before each of daily, backlog, batch and batchin restarts Postgres and drops the
-- OS cache. daily, backlog, batch and batchin roll back, so each step sees the same 120-day table.
\set ON_ERROR_STOP on
\if :{?rows_per_day}
\else
  \set rows_per_day 10000
\endif
\if :{?step}
\else
  \set step all
\endif
SELECT :'step' IN ('fill', 'all') AS do_fill, :'step' IN ('daily', 'all') AS do_daily,
       :'step' IN ('backlog', 'all') AS do_backlog, :'step' IN ('batch', 'all') AS do_batch,
       :'step' IN ('batchin', 'all') AS do_batchin, :'step' IN ('empty', 'all') AS do_empty \gset

\if :do_fill
DROP TABLE IF EXISTS audit;
CREATE TABLE audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_audit" PRIMARY KEY,
    at timestamp with time zone NOT NULL,
    kind character varying(16) NOT NULL,
    user_name character varying(256),
    endpoint character varying(256) NOT NULL,
    status integer NOT NULL,
    rows integer,
    ms integer NOT NULL,
    cache character varying(8)
);
CREATE INDEX "IX_audit_at" ON audit (at);

-- 120 days ending at a fixed "now"; synthetic users and endpoints like the real ones.
INSERT INTO audit (at, kind, user_name, endpoint, status, rows, ms, cache)
SELECT timestamptz '2026-10-08 12:00+00' - (g * (interval '120 days' / (:rows_per_day * 120))),
       'request',
       'viewer-' || (g % 7) || '@example.com',
       (ARRAY['GET /api/positions/rows', 'GET /api/positions/summary', 'GET /api/meta', 'GET /api/presets/{page}'])[1 + g % 4],
       200, 500, 12 + g % 90, (ARRAY['HIT', 'MISS'])[1 + g % 2]
FROM generate_series(1, :rows_per_day * 120) AS g;
VACUUM ANALYZE audit;

\echo '--- size with 120 days'
SELECT count(*) AS rows, pg_size_pretty(pg_total_relation_size('audit')) AS total,
       round(pg_total_relation_size('audit')::numeric / count(*), 1) AS bytes_per_row
FROM audit;
\endif

\if :do_daily
\echo '--- steady state: one daily purge (deletes the oldest day: 119 -> 120 days ago)'
BEGIN;
EXPLAIN (ANALYZE, BUFFERS, COSTS OFF, SUMMARY ON)
DELETE FROM audit WHERE at < timestamptz '2026-10-08 12:00+00' - interval '119 days';
ROLLBACK;
\endif

\if :do_backlog
\echo '--- backlog, one statement: 30 days past a 90-day window (300,000 rows)'
BEGIN;
EXPLAIN (ANALYZE, BUFFERS, COSTS OFF, SUMMARY ON)
DELETE FROM audit WHERE at < timestamptz '2026-10-08 12:00+00' - interval '90 days';
ROLLBACK;
\endif

\if :do_batch
\echo '--- backlog, first 50,000-row batch: the edge (index scan), then a time-range delete (AuditRetention.PurgeIfDueAsync)'
BEGIN;
EXPLAIN (ANALYZE, BUFFERS, COSTS OFF, SUMMARY ON)
SELECT a.at FROM audit AS a
WHERE a.at < timestamptz '2026-10-08 12:00+00' - interval '90 days'
ORDER BY a.at LIMIT 1 OFFSET 49999;
SELECT a.at AS edge FROM audit AS a
WHERE a.at < timestamptz '2026-10-08 12:00+00' - interval '90 days'
ORDER BY a.at LIMIT 1 OFFSET 49999 \gset
EXPLAIN (ANALYZE, BUFFERS, COSTS OFF, SUMMARY ON)
DELETE FROM audit AS a WHERE a.at <= :'edge';
ROLLBACK;
\endif

\if :do_batchin
\echo '--- for comparison, not used: the same batch as id IN (SELECT ... LIMIT), which EF emits for OrderBy.Take.ExecuteDelete'
BEGIN;
EXPLAIN (ANALYZE, BUFFERS, COSTS OFF, SUMMARY ON)
DELETE FROM audit AS a
WHERE a.id IN (
    SELECT a0.id FROM audit AS a0
    WHERE a0.at < timestamptz '2026-10-08 12:00+00' - interval '90 days'
    ORDER BY a0.at
    LIMIT 50000
);
ROLLBACK;
\endif

\if :do_empty
\echo '--- the 90-day purge, then the purge right after it (nothing to delete: the edge query finds no row)'
DELETE FROM audit WHERE at < timestamptz '2026-10-08 12:00+00' - interval '90 days';
EXPLAIN (ANALYZE, BUFFERS, COSTS OFF, SUMMARY ON)
SELECT a.at FROM audit AS a
WHERE a.at < timestamptz '2026-10-08 12:00+00' - interval '90 days'
ORDER BY a.at LIMIT 1 OFFSET 49999;
EXPLAIN (ANALYZE, BUFFERS, COSTS OFF, SUMMARY ON)
DELETE FROM audit WHERE at < timestamptz '2026-10-08 12:00+00' - interval '90 days';

VACUUM ANALYZE audit;
\echo '--- size with 90 days (after the purge and a vacuum; space is reused, not returned to the OS)'
SELECT count(*) AS rows, pg_size_pretty(pg_total_relation_size('audit')) AS total FROM audit;
\endif
