-- #133 / ADR-0008: EXPLAIN (ANALYZE, BUFFERS) for the first block of the unfiltered Risk view, sorted by each of the
-- four indexed columns, ascending and descending, with and without the index (#48 AC1).
-- Local stack only (never Render, Neon or production), seeded at scale 1.0 (about 20k rows per as-of date):
--   docker exec -i <postgres container> sh -c 'psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -q' < perf/explain-sort-indexes.sql
-- The query has the shape GridSqlBuilder.Build emits for the page (Risk preset columns, every portfolio, 200 rows).
-- "before" drops the index inside a transaction that is rolled back. Each plan runs once to warm the cache first.
\pset pager off
\set asof '''2026-10-06'''

\echo '=== market_value DESC: before (no ix_snapshot_sort_market_value)'
BEGIN;
DROP INDEX core.ix_snapshot_sort_market_value;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "market_value" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "market_value" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
ROLLBACK;
\echo '=== market_value DESC: after (ix_snapshot_sort_market_value)'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "market_value" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "market_value" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;

\echo '=== market_value ASC: before (no ix_snapshot_sort_market_value)'
BEGIN;
DROP INDEX core.ix_snapshot_sort_market_value;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "market_value" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "market_value" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
ROLLBACK;
\echo '=== market_value ASC: after (ix_snapshot_sort_market_value)'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "market_value" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "market_value" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;

\echo '=== spread_bp DESC: before (no ix_snapshot_sort_spread_bp)'
BEGIN;
DROP INDEX core.ix_snapshot_sort_spread_bp;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "spread_bp" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "spread_bp" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
ROLLBACK;
\echo '=== spread_bp DESC: after (ix_snapshot_sort_spread_bp)'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "spread_bp" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "spread_bp" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;

\echo '=== spread_bp ASC: before (no ix_snapshot_sort_spread_bp)'
BEGIN;
DROP INDEX core.ix_snapshot_sort_spread_bp;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "spread_bp" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "spread_bp" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
ROLLBACK;
\echo '=== spread_bp ASC: after (ix_snapshot_sort_spread_bp)'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "spread_bp" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "spread_bp" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;

\echo '=== dv01 DESC: before (no ix_snapshot_sort_dv01)'
BEGIN;
DROP INDEX core.ix_snapshot_sort_dv01;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "dv01" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "dv01" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
ROLLBACK;
\echo '=== dv01 DESC: after (ix_snapshot_sort_dv01)'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "dv01" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "dv01" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;

\echo '=== dv01 ASC: before (no ix_snapshot_sort_dv01)'
BEGIN;
DROP INDEX core.ix_snapshot_sort_dv01;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "dv01" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "dv01" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
ROLLBACK;
\echo '=== dv01 ASC: after (ix_snapshot_sort_dv01)'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "dv01" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "dv01" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;

\echo '=== deal_name DESC: before (no ix_snapshot_sort_deal_name)'
BEGIN;
DROP INDEX core.ix_snapshot_sort_deal_name;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "deal_name" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "deal_name" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
ROLLBACK;
\echo '=== deal_name DESC: after (ix_snapshot_sort_deal_name)'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "deal_name" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "deal_name" DESC, "position_id" DESC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;

\echo '=== deal_name ASC: before (no ix_snapshot_sort_deal_name)'
BEGIN;
DROP INDEX core.ix_snapshot_sort_deal_name;
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "deal_name" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "deal_name" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
ROLLBACK;
\echo '=== deal_name ASC: after (ix_snapshot_sort_deal_name)'
\o /dev/null
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "deal_name" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
\o
EXPLAIN (ANALYZE, BUFFERS) SELECT "position_id", "deal_name", "class", "cusip", "sector", "rating_composite", "current_face", "market_value", "unrealized_pnl", "pct_of_portfolio_mv", "price", "price_chg_1d", "yield", "spread_bp", "oas_bp", "dm_bp", "z_spread_bp", "spread_chg_1d_bp", "vendor_dispersion_bp", "mod_duration", "eff_duration", "convexity", "dv01", "krd_2y", "krd_5y", "krd_10y", "krd_20y", "krd_30y", "spread_duration", "cs01", "jtd", "expected_loss_pct", "credit_enhancement_pct", "wal", "coupon_current", "pnl_carry", "pnl_rates", "pnl_spread", "pnl_total_mtd", "worst_case_price", "stress_loss_mv", "watchlist_flag" FROM core.position_snapshot WHERE as_of_date = :asof AND portfolio_id = ANY('{1,2,3,4,5,6,7,8,9,10,11,12}'::int[]) ORDER BY "deal_name" ASC, "position_id" ASC OFFSET 0 ROWS FETCH NEXT 200 ROWS ONLY;
